FIXME: Try to fix coverage builds, failed
I was getting:

```
pkg/util/coverage/coverage.go:85: cannot use deps (variable of type fakeTestDeps) as type testing.testDeps in argument to testing.MainStart:
	fakeTestDeps does not implement testing.testDeps (missing CheckCorpus method)
```

But `testing.testDeps` is a private interface and some of those methods
use other private types (e.g. `corpusEntry`).  What the heck is going
on?