Remove manual validation of RC Replicas
First prove this is validated.

pkg/apis/core/validation/validation.go, func
ValidateReplicationControllerSpec() says:

```
	allErrs = append(allErrs, ValidateNonnegativeField(int64(spec.Replicas), fldPath.Child("replicas"))...)
```

pkg/apis/core/validation/validation_test.go, func
TestValidateReplicationController() says:

```
          "negative_replicas": {
              ObjectMeta: metav1.ObjectMeta{Name: "abc", Namespace: metav1.NamespaceDefault},
              Spec: core.ReplicationControllerSpec{
                  Replicas: -1,
                  Selector: validSelector,
              },
          },
```

So it seems like it is validated. Running tests before this commit passes:

```
$ go test -v -run TestValidateReplicationController ./pkg/apis/core/validation/
=== RUN   TestValidateReplicationControllerStatus
--- PASS: TestValidateReplicationControllerStatus (0.00s)
=== RUN   TestValidateReplicationControllerStatusUpdate
--- PASS: TestValidateReplicationControllerStatusUpdate (0.00s)
=== RUN   TestValidateReplicationControllerUpdate
--- PASS: TestValidateReplicationControllerUpdate (0.00s)
=== RUN   TestValidateReplicationController
--- PASS: TestValidateReplicationController (0.00s)
PASS
ok  	k8s.io/kubernetes/pkg/apis/core/validation	0.306s
```

Gate the manual validation (this commit):

```diff
diff --git a/pkg/apis/core/validation/validation.go b/pkg/apis/core/validation/validation.go
index 0cf6f922da5..b526ba6a2c2 100644
--- a/pkg/apis/core/validation/validation.go
+++ b/pkg/apis/core/validation/validation.go
@@ -5966,6 +5966,9 @@ func ValidateReplicationControllerSpec(spec, oldSpec *core.ReplicationController
 	allErrs := field.ErrorList{}
 	allErrs = append(allErrs, ValidateNonnegativeField(int64(spec.MinReadySeconds), fldPath.Child("minReadySeconds"))...)
 	allErrs = append(allErrs, ValidateNonEmptySelector(spec.Selector, fldPath.Child("selector"))...)
+	if !utilfeature.DefaultFeatureGate.Enabled(features.DeclarativeValidation) {
+		allErrs = append(allErrs, ValidateNonnegativeField(int64(spec.Replicas), fldPath.Child("replicas"))...)
+	}
 	allErrs = append(allErrs, ValidatePodTemplateSpecForRC(spec.Template, spec.Selector, spec.Replicas, fldPath.Child("template"), opts)...)
 	return allErrs
 }
```

The test should fail:

```
$ go test -v -run TestValidateReplicationController ./pkg/apis/core/validation/
=== RUN   TestValidateReplicationControllerStatus
--- PASS: TestValidateReplicationControllerStatus (0.00s)
=== RUN   TestValidateReplicationControllerStatusUpdate
--- PASS: TestValidateReplicationControllerStatusUpdate (0.00s)
=== RUN   TestValidateReplicationControllerUpdate
--- PASS: TestValidateReplicationControllerUpdate (0.00s)
=== RUN   TestValidateReplicationController
    validation_test.go:16709: case "negative_replicas": expected failure
--- FAIL: TestValidateReplicationController (0.00s)
FAIL
FAIL	k8s.io/kubernetes/pkg/apis/core/validation	0.299s
FAIL
```